name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ main, us/mcp-server-refactor-architecture ]  # TEMPORARY: Add for testing
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: windows-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Get version from tag or branch
      id: version
      shell: pwsh
      run: |
        if ($env:GITHUB_REF -match 'refs/tags/v(.+)') {
          $version = $matches[1]
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version from tag: $version"
        } else {
          $shortSha = $env:GITHUB_SHA.Substring(0, 7)
          $version = "1.0.0-dev-$shortSha"
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version from commit: $version"
        }

    - name: Restore dependencies
      run: dotnet restore DumpAnalyzer.sln

    - name: Build solution  
      run: dotnet build DumpAnalyzer.sln --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Run tests (if any)
      run: dotnet test DumpAnalyzer.sln --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --verbosity normal
      continue-on-error: true

    - name: Publish McpProxy
      run: |
        dotnet publish McpProxy/McpProxy.csproj `
          --configuration ${{ env.BUILD_CONFIGURATION }} `
          --runtime win-x64 `
          --output publish/win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:PublishTrimmed=false `
          -p:PublishReadyToRun=false `
          -p:Version=${{ steps.version.outputs.version }}

    - name: Publish BackgroundService
      run: |
        dotnet publish BackgroundService/BackgroundService.csproj `
          --configuration ${{ env.BUILD_CONFIGURATION }} `
          --runtime win-x64 `
          --output publish/win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:PublishTrimmed=false `
          -p:PublishReadyToRun=false `
          -p:Version=${{ steps.version.outputs.version }}

    - name: Create portable package
      shell: pwsh
      run: |
        $version = "${{ steps.version.outputs.version }}"
        
        Write-Host "📦 Creating WinDbg MCP Server package v$version"
        
        # Create package directory
        New-Item -ItemType Directory -Path "package" -Force
        
        # Copy executables (with validation)
        if (Test-Path "publish/win-x64/*.exe") {
          Copy-Item "publish/win-x64/*.exe" "package/" -Force
          Write-Host "✅ Copied executables"
        } else {
          Write-Error "❌ No executables found in publish/win-x64/"
          exit 1
        }
        Copy-Item "publish/win-x64/*.pdb" "package/" -Force -ErrorAction SilentlyContinue
        
        # Copy scripts
        if (Test-Path "Scripts/") {
          Copy-Item "Scripts/" "package/Scripts/" -Recurse -Force
          Write-Host "✅ Copied Scripts folder"
        }
        
        # Copy documentation
        Copy-Item "README.md" "package/" -Force -ErrorAction Stop
        Copy-Item "LICENSE" "package/" -Force -ErrorAction SilentlyContinue
        Copy-Item "CLAUDE.md" "package/" -Force -ErrorAction Stop
        
        # Copy configuration examples  
        Copy-Item "claude-mcp-config.json" "package/" -Force -ErrorAction Stop
        if (Test-Path "Tests/") {
          Copy-Item "Tests/" "package/Examples/" -Recurse -Force
          Write-Host "✅ Copied Tests as Examples"
        }
        
        # Create version info file
        $versionContent = @"
        WinDbg MCP Server v$version
        Built on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')
        Commit: $env:GITHUB_SHA
        
        Files included:
        - McpProxy.exe (Main MCP server executable)
        - BackgroundService.exe (Background processing service)
        - Scripts/ (PowerShell scripts for standalone usage)
        - README.md (Complete documentation)
        - CLAUDE.md (Claude Code integration instructions)
        - claude-mcp-config.json (Configuration example)
        - Examples/ (Usage examples)
        
        Quick start:
        1. Run McpProxy.exe to start the MCP server
        2. Configure Claude Code with claude-mcp-config.json
        3. Use Scripts/cdb.ps1 for standalone dump analysis
        
        For detailed instructions, see README.md
        "@
        $versionContent | Out-File -FilePath "package/VERSION.txt" -Encoding UTF8
        
        # Create ZIP package
        $packageName = "windbg-mcp-server-v$version-win-x64"
        Compress-Archive -Path "package/*" -DestinationPath "$packageName.zip" -Force
        
        Write-Host "✅ Created package: $packageName.zip"
        echo "package-name=$packageName" >> $env:GITHUB_OUTPUT
        echo "package-path=$packageName.zip" >> $env:GITHUB_OUTPUT
        
        # List package contents for verification
        Write-Host "📦 Package contents:"
        Get-ChildItem "package/" -Recurse | ForEach-Object { 
          $relativePath = $_.FullName.Replace((Resolve-Path "package/").Path, "")
          Write-Host "  $relativePath"
        }
        
        # Validate required files exist
        $requiredFiles = @("McpProxy.exe", "BackgroundService.exe", "README.md", "CLAUDE.md")
        foreach ($file in $requiredFiles) {
          if (Test-Path "package/$file") {
            Write-Host "✅ Found required file: $file"
          } else {
            Write-Error "❌ Missing required file: $file"
            exit 1
          }
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windbg-mcp-server-${{ steps.version.outputs.version }}
        path: |
          *.zip
          package/

  # Diagnostic job to test permissions and token
  diagnose:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/us/mcp-server-refactor-architecture' || github.event_name == 'workflow_dispatch'  # TEMPORARY: Test branch or manual trigger
    permissions:
      contents: write
      actions: read
      issues: read
    steps:
    - name: Debug GitHub Context
      shell: pwsh
      run: |
        Write-Host "🔍 Debugging GitHub token permissions..."
        Write-Host "Repository: ${{ github.repository }}"
        Write-Host "Actor: ${{ github.actor }}"
        Write-Host "Event: ${{ github.event_name }}"
        Write-Host "Ref: ${{ github.ref }}"
        Write-Host "Token available: ${{ secrets.GITHUB_TOKEN != '' }}"

    - name: Test GitHub API Access
      shell: pwsh
      run: |
        $headers = @{
          'Authorization' = 'token ${{ secrets.GITHUB_TOKEN }}'
          'Accept' = 'application/vnd.github.v3+json'
        }

        try {
          Write-Host "🔑 Testing GitHub API permissions..."
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}" -Headers $headers
          Write-Host "✅ Repository access: OK"

          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases" -Headers $headers
          Write-Host "✅ Releases read access: OK ($($response.Count) releases found)"

          # Test creating a draft release (will be deleted)
          $testRelease = @{
            tag_name = "test-permissions-delete-me"
            name = "Test Permission Release (DELETE ME)"
            body = "Testing permissions - this should be deleted"
            draft = $true
          } | ConvertTo-Json -Compress

          $createResponse = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases" -Method POST -Headers $headers -Body $testRelease -ContentType "application/json"
          Write-Host "✅ Release create access: OK (ID: $($createResponse.id))"

          # Clean up test release
          Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/$($createResponse.id)" -Method DELETE -Headers $headers
          Write-Host "✅ Test release cleaned up"

        } catch {
          Write-Error "❌ API Error: $($_.Exception.Message)"
          Write-Error "Response: $($_.ErrorDetails.Message)"
        }

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: windbg-mcp-server-${{ needs.build.outputs.version }}

    - name: Create Release Body
      id: release_body
      shell: pwsh
      run: |
        $body = @"
        ## WinDbg MCP Server ${{ needs.build.outputs.version }}
        
        Windows memory dump analysis tool with MCP (Model Context Protocol) integration.
        
        ### Features
        - Interactive debugging with persistent WinDbg/CDB sessions
        - 10 types of predefined analyses (basic, exception, threads, heap, etc.)
        - Claude Code integration via MCP protocol
        - Visual Studio Code and GitHub Copilot integration
        - Automatic debugger detection (Windows SDK, WinDbg Store App)
        - Single-file executable deployment
        
        ### What's included
        - ``McpProxy.exe`` - Main MCP server executable
        - ``BackgroundService.exe`` - Background processing service  
        - ``Scripts/`` - PowerShell scripts for standalone usage
        - ``README.md`` - Complete documentation and integration guide
        - ``claude-mcp-config.json`` - Configuration example for Claude Code
        - ``Examples/`` - Usage examples and test files
        
        ### Quick Start
        1. Download and extract the ZIP file
        2. Run ``McpProxy.exe`` to start the MCP server
        3. Configure Claude Code using the provided config example
        4. See ``README.md`` for detailed integration instructions
        
        ### Requirements
        - Windows 10/11
        - .NET 8.0 runtime (included in single-file executable)
        - Windows SDK Debuggers (cdb.exe) or WinDbg from Microsoft Store
        
        For detailed documentation, see [README.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/README.md).
        "@
        echo "body<<EOF" >> $env:GITHUB_OUTPUT
        echo $body >> $env:GITHUB_OUTPUT
        echo "EOF" >> $env:GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: WinDbg MCP Server ${{ needs.build.outputs.version }}
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.release_body.outputs.body }}
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        files: "*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}